custom_tokenizer_path: math_tokenizer_data


weight_decay: 1e-2

max_new_tokens: 1
max_expression_terms: 2
print_every: 500
save_every: 5000

context_length:   32
embedding_size:   384
num_heads:        6
num_layers:       4
feed_forward_size: 1536
dropout_rate:     0.1

learning_rate:    0.002
batch_size:       128
baseline_momentum: 0.5
num_updates:      50000
