# dtype: bfloat16
# compute_dtype: bfloat16
param_dtype: float32
dtype: float16
compute_dtype: float16
# param_dtype: float16

tokenizer_name: EleutherAI/gpt-neo-125M
tokenizer_path: tiny_cached
tokenizer_dtype: uint16
use_custom_tokenizer: true
custom_tokenizer_path: math_tokenizer_data

# DATASET_VENDOR = "Salesforce/wikitext"
# DATASET_NAME   = "wikitext-2-raw-v1"
dataset_name: wikitext-2-raw-v1
dataset_has_vendor: true
dataset_vendor: Salesforce
# dataset_name: roneneldan/TinyStories
# dataset_has_vendor: false
# dataset_vendor: roneneldan
use_custom_dataset: true
dataset_path: math_dataset_arrow


# model:
embedding_size: 384
context_length: 385
num_heads: 4
num_layers: 4
feed_forward_size: 1536
dropout_rate: 0.1

# training:
learning_rate: 1e-4
weight_decay: 1e-4
batch_size: 6
num_epochs: 3
acc_steps: 2

# other:
use_remat: true
dataset_percent: 30
chunk_percent: 10
default_device: cuda
