custom_tokenizer_path: math_tokenizer_data
context_length: 32


embedding_size: 256
num_heads: 2
num_layers: 2
feed_forward_size: 1024
dropout_rate: 0.1


learning_rate: 5e-5
weight_decay: 1e-2


num_updates: 50000
batch_size: 64
baseline_momentum: 0.9
max_new_tokens: 1
max_expression_terms: 2
print_every: 500
save_every: 5000

