[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "toy_vllm_model"
version = "0.0.1"
dependencies = [
  "vllm>=0.13.0",
  "torch",
  "transformers",
  "safetensors",
]

[project.entry-points."vllm.general_plugins"]
register_toy_decoder = "toy_vllm_model.plugin:register"
