/*
"""
Finding_Free_token_slots_A40.typ
Experiment runbook and provenance note

Goal
- This file is a consolidated A40 performance notebook for TiDAR decode-path analysis.
- It combines:
  1) decode attention cost curves,
  2) MLP-only scaling curves,
  3) staged decode path vs single-pass behavior notes,
  4) isolated sampling microbenchmarks,
  5) AR (batch=1) vs TiDAR sampling-only comparisons by K,
  6) a recent whole-generation TiDAR vs AR style sanity check at 3b.

How to read this document
- Section 1: "A40 Decode Attention Speed (Final)"
  - Attention-only timing curves over K in {2,4,8,16}
  - Includes kernel-level and native decode-path style measurements.
- Section 2: "A40 MLP Throughput - AR vs TiDAR Tokens"
  - MLP-only scaling curves (AR len=1 scaled by K vs TiDAR L=K+K^2).
- Section 3: "A40 Greedy Decode: Staged Softmax vs Greedy No-Softmax"
  - End-to-end decode (small deltas) plus isolated sampling deltas.
- Section 4: "A40 Isolated Sampling: AR (B=1) vs TiDAR by K"
  - Sampling-only AR scaled baseline vs TiDAR staged path for greedy and non-greedy.

Main code paths touched or relied upon
- TiDAR inference logic:
  - TiDAR/model/inference.py
  - TiDAR/model/tidar_core.py
  - TiDAR/model/config_schema.py
- TiDAR controlled-throughput harness:
  - TiDAR/model/test_inference_througthput.py
- AR reference decode style:
  - GIANT/v2/model/Generate_faster.py
  - GIANT/v2/model/jit_inference.py
  - GIANT/v2/model/GiantGPT.py
- Decode attention benchmark script:
  - TiDAR/tests/benchmark_decode_attention_speed.py

Configs used as references in this file
- TiDAR A40 narrow benchmark configs:
  - TiDAR/Docs/Benchmark_logs/tidar_updated_narrow_20260208_094343/configs/config_500m.yml
  - TiDAR/Docs/Benchmark_logs/tidar_updated_narrow_20260208_094343/configs/config_1b.yml
  - TiDAR/Docs/Benchmark_logs/tidar_updated_narrow_20260208_094343/configs/config_3b.yml
- Global path roots:
  - TiDAR/Global_Config.yml
  - GIANT/v2/Global_Config.yml

Known logs/artifacts referenced by this file (local workstation)
- Isolated sampling AR-vs-TiDAR-by-K sweep on A40:
  - /tmp/tidar_sampling_ar_vs_k_bench.py
  - /tmp/tidar_sampling_ar_vs_k_a40_output.txt
- Whole-generation compare at 3b, prefill=2048, steps=256:
  - /tmp/run_tidar_wholegen_compare.py
  - /tmp/run_ar_generate_faster_style_3b.py
  - /tmp/tidar_3b_k16_acc08_pref2048_verbose.log
  - /tmp/ar_3b_generate_faster_style_pref2048_verbose.log

Remote execution context for recent runs
- Remote host: root@gpu-box-1
- GPU: NVIDIA A40
- Typical invocation pattern:
  - sync local edits to remote repo (or copy exact files/scripts),
  - run /opt/venv/bin/python scripts remotely,
  - store verbose logs under /tmp and pull/inspect locally.

Repro command templates (examples)
- Decode attention benchmark (A40):
  - /opt/venv/bin/python TiDAR/tests/benchmark_decode_attention_speed.py \
      --implementation cudnn --batch_size 1 --prefix_len 1024 --iterations 100 --repeats 5 \
      --draft_len 2|4|8|16 --num_heads ... --num_kv_heads ... --head_dim ...
- Controlled TiDAR throughput:
  - /opt/venv/bin/python TiDAR/model/test_inference_througthput.py \
      --config <cfg.yml> --global_config TiDAR/Global_Config.yml \
      --draft_len <K> --accept-rate <p> --prefill_tokens <N> --steps <S>
- AR style throughput (Generate_faster path):
  - /opt/venv/bin/python GIANT/v2/model/Generate_faster.py \
      --checkpoint <ckpt_or_latest> --steps <S> --temperature <T> --top_k <K> --verbose

Important caveats for continuation
- This .typ file contains hand-curated constants for several plots.
- Not every section is generated by one single checked-in script.
- MLP-only section values are embedded directly in this document.
- /tmp scripts/logs are ephemeral; if this doc becomes a long-lived benchmark source,
  move generator scripts into TiDAR/tests/ or TiDAR/Docs/scripts/ and store logs under
  TiDAR/Docs/Benchmark_logs/<timestamp>/ for traceability.

Recent whole-generation sanity check summary (A40, 3b profile)
- TiDAR staged, draft_len=16, accept_rate=0.8, prefill=2048, steps=256:
  - tokens_per_second_decode_only: 19.409182
  - tokens_per_second_whole_gen:   18.398439
- AR Generate_faster style at matching 3b profile and prefill/steps:
  - tokens_per_second_decode_only: 18.721542
  - tokens_per_second_whole_gen:    2.157842
- Logs:
  - /tmp/tidar_3b_k16_acc08_pref2048_verbose.log
  - /tmp/ar_3b_generate_faster_style_pref2048_verbose.log
"""
*/

#set page(width: 210mm, height: 297mm, margin: 12mm)
#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: none)

#let c-k-structured = rgb("#1D4ED8")
#let c-k-dense = rgb("#DC2626")
#let c-k-densezero = rgb("#059669")
#let c-ar = rgb("#7C3AED")
#let c-n-structured = rgb("#1D4ED8")
#let c-n-dense = rgb("#DC2626")
#let c-mlp-ar = rgb("#7C3AED")
#let c-mlp-tidar = rgb("#0F766E")

#let legend-item(label, color) = grid(
  columns: (auto, auto),
  gutter: 4pt,
  align: left,
  rect(width: 8pt, height: 8pt, fill: color, radius: 1.4pt),
  text(size: 8.5pt)[#label],
)

#let line-chart(
  title,
  series,
  width: 182mm,
  height: 62mm,
  x-label: "draft_len (K)",
  y-label: "ms / attention",
  y-label-dx: 3pt,
) = {
  let margin-left = 28pt
  let margin-right = 8pt
  let margin-top = 12pt
  let margin-bottom = 26pt
  let plot-width = width - margin-left - margin-right
  let plot-height = height - margin-top - margin-bottom

  let min-x = calc.min(..series.map(s => calc.min(..s.data.map(d => d.at(0)))))
  let max-x = calc.max(..series.map(s => calc.max(..s.data.map(d => d.at(0)))))
  let max-y-data = calc.max(..series.map(s => calc.max(..s.data.map(d => d.at(1)))))
  let min-y = 0.0
  let max-y = max-y-data * 1.08

  let sx = if max-x == min-x { plot-width } else { plot-width / (max-x - min-x) }
  let sy = if max-y == min-y { plot-height } else { plot-height / (max-y - min-y) }

  let x-ticks = (2, 4, 8, 16)
  let y-ticks = range(0, 6)

  block(width: width, height: height, inset: 5pt, stroke: 0.7pt + rgb("#D1D5DB"), radius: 6pt)[
    #text(weight: "semibold", size: 9.4pt)[#title]
    #v(2pt)
    #place(top + left, dx: margin-left, dy: margin-top + plot-height)[
      #line(length: plot-width, stroke: 0.6pt + black)
    ]
    #place(top + left, dx: margin-left, dy: margin-top)[
      #line(length: plot-height, angle: 90deg, stroke: 0.6pt + black)
    ]

    #for t in y-ticks [
      #let yv = min-y + (max-y - min-y) * (t / 5)
      #let py = margin-top + plot-height - (yv - min-y) * sy
      #place(top + left, dx: margin-left, dy: py)[
        #line(length: plot-width, stroke: (paint: rgb("#E5E7EB"), thickness: 0.45pt, dash: (2pt, 2pt)))
      ]
      #place(top + left, dx: 1pt, dy: py - 4pt)[
        #text(size: 7pt, fill: rgb("#4B5563"))[#(str(calc.round(yv, digits: 3)))]
      ]
    ]

    #for xv in x-ticks [
      #let px = margin-left + (xv - min-x) * sx
      #place(top + left, dx: px, dy: margin-top + plot-height)[
        #line(length: 3pt, angle: 90deg, stroke: 0.6pt + black)
      ]
      #place(top + left, dx: px - 4pt, dy: margin-top + plot-height + 4pt)[
        #text(size: 8pt)[#(str(xv))]
      ]
    ]

    #for s in series [
      #place(top + left, dx: margin-left, dy: margin-top)[
        #path(
          stroke: 1.2pt + s.color,
          fill: none,
          ..s.data.map(d => (
            (d.at(0) - min-x) * sx,
            plot-height - (d.at(1) - min-y) * sy,
          )),
        )
      ]
      #for d in s.data [
        #let px = margin-left + (d.at(0) - min-x) * sx
        #let py = margin-top + plot-height - (d.at(1) - min-y) * sy
        #place(top + left, dx: px - 1.4pt, dy: py - 1.4pt)[
          #circle(radius: 1.4pt, fill: s.color)
        ]
      ]
    ]

    #place(top + left, dx: margin-left, dy: margin-top + plot-height + 9pt)[
      #text(size: 7.8pt)[#x-label]
    ]
    #place(top + left, dx: y-label-dx, dy: margin-top + plot-height / 2 - 16pt)[
      #rotate(-90deg)[#text(size: 7.8pt)[#y-label]]
    ]
  ]
}

#let chart-block(title, series) = [
  #block(breakable: false)[
    #text(weight: "semibold", size: 9.4pt)[#title]
    #v(1pt)
    #for s in series [
      #legend-item(s.label, s.color)
      #h(9pt)
    ]
    #v(1pt)
    #line-chart("", series)
  ]
]

#let k1b = (
  (label: "kernel structured", color: c-k-structured, data: ((2, 0.107145), (4, 0.126596), (8, 0.152638), (16, 0.181612))),
  (label: "kernel dense", color: c-k-dense, data: ((2, 0.071736), (4, 0.070505), (8, 0.074565), (16, 0.087710))),
  (label: "kernel dense+jax-zero", color: c-k-densezero, data: ((2, 0.038555), (4, 0.049070), (8, 0.086636), (16, 0.256265))),
  (label: "AR baseline (K x len1)", color: c-ar, data: ((2, 0.065535), (4, 0.131070), (8, 0.262139), (16, 0.524278))),
)

#let n1b = (
  (label: "native structured", color: c-n-structured, data: ((2, 0.412120), (4, 0.433505), (8, 0.451159), (16, 0.543223))),
  (label: "native dense", color: c-n-dense, data: ((2, 0.391434), (4, 0.410521), (8, 0.432730), (16, 0.547173))),
  (label: "AR baseline (K x len1)", color: c-ar, data: ((2, 0.522547), (4, 1.045094), (8, 2.090188), (16, 4.180376))),
)

#let k3b = (
  (label: "kernel structured", color: c-k-structured, data: ((2, 0.075724), (4, 0.076048), (8, 0.081382), (16, 0.097438))),
  (label: "kernel dense", color: c-k-dense, data: ((2, 0.069547), (4, 0.069569), (8, 0.074939), (16, 0.088723))),
  (label: "kernel dense+jax-zero", color: c-k-densezero, data: ((2, 0.048804), (4, 0.058910), (8, 0.085520), (16, 0.225689))),
  (label: "AR baseline (K x len1)", color: c-ar, data: ((2, 0.087481), (4, 0.174962), (8, 0.349925), (16, 0.699849))),
)

#let n3b = (
  (label: "native structured", color: c-n-structured, data: ((2, 0.531247), (4, 0.540576), (8, 0.554605), (16, 0.706373))),
  (label: "native dense", color: c-n-dense, data: ((2, 0.527241), (4, 0.535066), (8, 0.547967), (16, 0.699304))),
  (label: "AR baseline (K x len1)", color: c-ar, data: ((2, 0.697389), (4, 1.394777), (8, 2.789555), (16, 5.579110))),
)

#let k7b = (
  (label: "kernel structured", color: c-k-structured, data: ((2, 0.075419), (4, 0.078492), (8, 0.082303), (16, 0.171602))),
  (label: "kernel dense", color: c-k-dense, data: ((2, 0.070653), (4, 0.072270), (8, 0.075352), (16, 0.157649))),
  (label: "kernel dense+jax-zero", color: c-k-densezero, data: ((2, 0.056792), (4, 0.067157), (8, 0.109234), (16, 0.288356))),
  (label: "AR baseline (K x len1)", color: c-ar, data: ((2, 0.100167), (4, 0.200334), (8, 0.400669), (16, 0.801337))),
)

#let n7b = (
  (label: "native structured", color: c-n-structured, data: ((2, 0.793903), (4, 0.793006), (8, 0.815991), (16, 1.071996))),
  (label: "native dense", color: c-n-dense, data: ((2, 0.781417), (4, 0.786742), (8, 0.811170), (16, 1.061794))),
  (label: "AR baseline (K x len1)", color: c-ar, data: ((2, 1.315679), (4, 2.631358), (8, 5.262716), (16, 10.525433))),
)

= A40 Decode Attention Speed (Final)

Runs: `A40 spot`, `bf16`, `implementation=cudnn`, `prefix_len=1024`, `iterations=100`, `repeats=5`, `batch_size=1`.

#text(size: 8.5pt, fill: rgb("#4B5563"))[
Pallas series is intentionally omitted from these plots to keep the non-pallas curves readable on a single scale.
AR baseline is measured at batch=1, query_len=1 and scaled by `K` for each draft length point.
]

#v(7pt)

#chart-block("1B-style MHA (32/32, head_dim 64) - Kernel terms", k1b)
#v(7pt)
#chart-block("1B-style MHA (32/32, head_dim 64) - Native decode", n1b)
#v(7pt)
#chart-block("3B-style GQA (24/8, head_dim 128) - Kernel terms", k3b)
#v(7pt)
#chart-block("3B-style GQA (24/8, head_dim 128) - Native decode", n3b)
#v(7pt)
#chart-block("7B-style GQA (32/8, head_dim 128) - Kernel terms", k7b)
#v(7pt)
#chart-block("7B-style GQA (32/8, head_dim 128) - Native decode", n7b)

#pagebreak()

= A40 MLP Throughput — AR vs TiDAR Tokens

This section compares MLP-only cost using SwiGLU projections. AR baseline is measured on `len=1` and scaled by `K`, while TiDAR runs the full `L = K + K^2` token block in one pass.

#let mlp1b = (
  (label: "TiDAR MLP at L=K+K^2", color: c-mlp-tidar, data: ((2, 0.184439), (4, 0.193440), (8, 0.210385), (16, 0.406673))),
  (label: "AR MLP baseline (K x len1)", color: c-mlp-ar, data: ((2, 0.368354), (4, 0.736707), (8, 1.473414), (16, 2.946828))),
)

#let mlp3b = (
  (label: "TiDAR MLP at L=K+K^2", color: c-mlp-tidar, data: ((2, 0.264362), (4, 0.279314), (8, 0.304600), (16, 0.595783))),
  (label: "AR MLP baseline (K x len1)", color: c-mlp-ar, data: ((2, 0.539437), (4, 1.078875), (8, 2.157750), (16, 4.315500))),
)

#let mlp7b = (
  (label: "TiDAR MLP at L=K+K^2", color: c-mlp-tidar, data: ((2, 0.462071), (4, 0.484772), (8, 0.554393), (16, 1.085345))),
  (label: "AR MLP baseline (K x len1)", color: c-mlp-ar, data: ((2, 0.926167), (4, 1.852334), (8, 3.704667), (16, 7.409334))),
)

#chart-block("1B-style MHA (d_model=2048, d_ff=8192) - MLP only", mlp1b)
#v(7pt)
#chart-block("3B-style GQA (d_model=3072, d_ff=8192) - MLP only", mlp3b)
#v(7pt)
#chart-block("7B-style GQA (d_model=4096, d_ff=11008) - MLP only", mlp7b)

#pagebreak()

= A40 Greedy Decode: Staged Softmax vs Greedy No-Softmax

This section separates two different measurements to avoid mixing signals:

- End-to-end full decode pass (includes full model forward cost).
- Isolated sampling microbenchmark (focuses on candidate sampling/rejection/commit path only).

#let c-greedy-base = rgb("#64748B")
#let c-greedy-opt = rgb("#0F766E")
#let c-greedy-delta = rgb("#1D4ED8")
#let c-micro-0 = rgb("#0E7490")
#let c-micro-50 = rgb("#B45309")

#let greedy-rows = (
  (model: "500m", baseline_tps: 62.008792, optimized_tps: 62.090169, delta_pct: 0.131),
  (model: "1b",   baseline_tps: 210.791055, optimized_tps: 210.854329, delta_pct: 0.030),
  (model: "3b",   baseline_tps: 63.215257, optimized_tps: 63.256417, delta_pct: 0.065),
)

#let delta-bar-chart(
  title,
  rows,
  bar-color: c-greedy-delta,
  width: 182mm,
  height: 60mm,
  title-size: 9.4pt,
) = {
  let margin-left = 30pt
  let margin-right = 8pt
  let margin-top = 12pt
  let margin-bottom = 24pt
  let plot-width = width - margin-left - margin-right
  let plot-height = height - margin-top - margin-bottom

  let max-y-data = calc.max(..rows.map(r => r.delta_pct))
  let max-y = max-y-data * 1.12
  let step = plot-width / rows.len()
  let bar-width = 14pt
  let y-ticks = range(0, 6)

  block(width: width, height: height, inset: 5pt, stroke: 0.7pt + rgb("#D1D5DB"), radius: 6pt)[
    #text(weight: "semibold", size: title-size)[#title]
    #v(2pt)
    #place(top + left, dx: margin-left, dy: margin-top + plot-height)[
      #line(length: plot-width, stroke: 0.6pt + black)
    ]
    #place(top + left, dx: margin-left, dy: margin-top)[
      #line(length: plot-height, angle: 90deg, stroke: 0.6pt + black)
    ]

    #for t in y-ticks [
      #let yv = max-y * (t / 5)
      #let py = margin-top + plot-height - (yv / max-y) * plot-height
      #place(top + left, dx: margin-left, dy: py)[
        #line(length: plot-width, stroke: (paint: rgb("#E5E7EB"), thickness: 0.45pt, dash: (2pt, 2pt)))
      ]
      #place(top + left, dx: 1pt, dy: py - 4pt)[
        #text(size: 7pt, fill: rgb("#4B5563"))[#(str(calc.round(yv, digits: 3)))]
      ]
    ]

    #for i in range(rows.len()) [
      #let r = rows.at(i)
      #let cx = margin-left + (i + 0.5) * step
      #let h = (r.delta_pct / max-y) * plot-height

      #place(top + left, dx: cx - bar-width / 2, dy: margin-top + plot-height - h)[
        #rect(width: bar-width, height: h, fill: bar-color, radius: 1.8pt)
      ]
      #place(top + left, dx: cx - 7pt, dy: margin-top + plot-height + 5pt)[
        #text(size: 8pt)[#r.model]
      ]
      #place(top + left, dx: cx - 12pt, dy: margin-top + plot-height - h - 10pt)[
        #text(size: 7.3pt, fill: rgb("#1F2937"))[#(str(calc.round(r.delta_pct, digits: 3))) + "%"]
      ]
    ]
  ]
}

#block(breakable: false)[
  #text(weight: "semibold", size: 10pt)[End-to-end full decode (A40, draft_len=8, prefill_tokens=1024, single pass)]
  #v(2pt)
  #text(size: 8.7pt)[
    These gains are very small and near noise floor for one-pass runs:
  ]
  #v(2pt)
  - `500m`: `62.0088 -> 62.0902` tokens/s (`+0.131%`)
  - `1b`: `210.7911 -> 210.8543` tokens/s (`+0.030%`)
  - `3b`: `63.2153 -> 63.2564` tokens/s (`+0.065%`)
  #v(1pt)
  #text(size: 8.5pt, fill: rgb("#4B5563"))[
    Mean speedup across these three runs: `+0.075%`.
  ]
]

#v(8pt)

#block(breakable: false)[
  #text(weight: "semibold", size: 10pt)[Isolated sampling microbenchmark (not full forward pass)]
  #v(2pt)
  #text(size: 8.7pt)[
    Benchmark definition:
  ]
  #v(1pt)
  - Old path: sample `K` (verify) + sample `K^2` (all predraft rows) + determine row + commit.
  - New path: sample `K` (verify) + determine row + sample selected `K` row only + commit.
  #v(3pt)
  #text(size: 8.6pt, fill: rgb("#4B5563"))[
    The following deltas are from this isolated sampling path and are not end-to-end decode speedups.
  ]
]

#let micro-topk0 = (
  (model: "K=4", delta_pct: 29.64),
  (model: "K=8", delta_pct: 127.45),
  (model: "K=16", delta_pct: 320.57),
)

#let micro-topk50 = (
  (model: "K=4", delta_pct: 88.94),
  (model: "K=8", delta_pct: 67.68),
  (model: "K=16", delta_pct: 225.23),
)

#v(5pt)
#block(breakable: false)[
  #legend-item("new path speedup over old path", c-micro-0)
  #v(2pt)
  #delta-bar-chart("Isolated sampling speedup (%) - top_k=0", micro-topk0, bar-color: c-micro-0)
]

#v(8pt)
#block(breakable: false)[
  #legend-item("new path speedup over old path", c-micro-50)
  #v(2pt)
  #delta-bar-chart("Isolated sampling speedup (%) - top_k=50", micro-topk50, bar-color: c-micro-50)
]

#pagebreak()

= A40 Isolated Sampling: AR (B=1) vs TiDAR by K

This page isolates only the sampling/rejection path (no transformer forward) and compares:

- AR baseline sampled at `batch=1`, `len=1`, then scaled by `K` (`K x len1`) for parity with TiDAR committed-token span.
- TiDAR staged path (sample verify, reject/select, sample only selected predraft row).
- Single fixed setup for this sweep: `prefix_len=1024`, vocab `49152`, `A40`.
- Variants: greedy (`temperature=0`, `top_k=0`) and non-greedy (`temperature=1`, `top_k=50`).

#let c-samp-ar-g = rgb("#7C3AED")
#let c-samp-ti-g = rgb("#0F766E")
#let c-samp-ar-ng = rgb("#DC2626")
#let c-samp-ti-ng = rgb("#EAB308")

#let sampling-chart-block(title, series) = [
  #block(breakable: false)[
    #text(weight: "semibold", size: 9.4pt)[#title]
    #v(1pt)
    #for s in series [
      #legend-item(s.label, s.color)
      #h(8pt)
    ]
    #v(1pt)
    #line-chart("", series, y-label: "ms / sampling cycle")
  ]
]

#let samp500 = (
  (label: "AR scaled (K x len1), greedy", color: c-samp-ar-g, data: ((2, 0.039421), (4, 0.078841), (8, 0.157683), (16, 0.315365))),
  (label: "TiDAR staged sampling, greedy", color: c-samp-ti-g, data: ((2, 0.030588), (4, 0.031840), (8, 0.028928), (16, 0.045513))),
  (label: "AR scaled (K x len1), non-greedy top_k=50", color: c-samp-ar-ng, data: ((2, 0.195142), (4, 0.390284), (8, 0.780567), (16, 1.561134))),
  (label: "TiDAR staged sampling, non-greedy top_k=50", color: c-samp-ti-ng, data: ((2, 0.373429), (4, 0.520660), (8, 0.684784), (16, 1.264817))),
)

#let samp1b = (
  (label: "AR scaled (K x len1), greedy", color: c-samp-ar-g, data: ((2, 0.037155), (4, 0.074310), (8, 0.148621), (16, 0.297241))),
  (label: "TiDAR staged sampling, greedy", color: c-samp-ti-g, data: ((2, 0.027033), (4, 0.028246), (8, 0.031896), (16, 0.046360))),
  (label: "AR scaled (K x len1), non-greedy top_k=50", color: c-samp-ar-ng, data: ((2, 0.188041), (4, 0.376083), (8, 0.752166), (16, 1.504332))),
  (label: "TiDAR staged sampling, non-greedy top_k=50", color: c-samp-ti-ng, data: ((2, 0.371912), (4, 0.519616), (8, 0.688824), (16, 1.263938))),
)

#let samp3b = (
  (label: "AR scaled (K x len1), greedy", color: c-samp-ar-g, data: ((2, 0.037177), (4, 0.074355), (8, 0.148710), (16, 0.297420))),
  (label: "TiDAR staged sampling, greedy", color: c-samp-ti-g, data: ((2, 0.027095), (4, 0.031905), (8, 0.031948), (16, 0.044603))),
  (label: "AR scaled (K x len1), non-greedy top_k=50", color: c-samp-ar-ng, data: ((2, 0.195230), (4, 0.390460), (8, 0.780921), (16, 1.561842))),
  (label: "TiDAR staged sampling, non-greedy top_k=50", color: c-samp-ti-ng, data: ((2, 0.369163), (4, 0.522335), (8, 0.685281), (16, 1.270568))),
)

#sampling-chart-block("500m sampling-only: AR scaled vs TiDAR staged", samp500)
#v(7pt)
#sampling-chart-block("1b sampling-only: AR scaled vs TiDAR staged", samp1b)
#v(7pt)
#sampling-chart-block("3b sampling-only: AR scaled vs TiDAR staged", samp3b)

#v(4pt)
#text(size: 8.4pt, fill: rgb("#4B5563"))[
Greedy curves show strong TiDAR sampling advantage as `K` grows. In non-greedy `top_k=50`, TiDAR crosses over from slower at low `K` (`2,4`) to faster at higher `K` (`8,16`).
]
