model_name: "clowman/Llama-3.2-3B-Instruct-AWQ-Int4"
model_tokenizer: "clowman/Llama-3.2-3B-Instruct-AWQ-Int4"
model_base_url: "http://0.0.0.0:8000/v1"
api_key: "banangun3000"

max_model_len: 2048
temperature: 1.5
top_p: 0.7
top_logprobs: 8
prompt_logprobs: 0

out_dir: "teacher_out"
questions_arrow: "teacher_out/questions.arrow"
answers_arrow: "teacher_out/answers.arrow"

student_tokenizer_name: "clowman/Llama-3.2-3B-Instruct-AWQ-Int4"
user_token: "user"
ai_token: "assistant"

# for these make sure they match the neo tokenizer config, because saw it uses mask for pads and so on.
write_loss_mask: true  
write_role_ids: true

# Generation:
num_questions_total: 10000
questions_per_chunk: 1000

max_new_tokens_answer: 256

parrallel_calls: 32

# Prompts:
question_system: "You are a teacher language model who is needed to generate questions for a chat interaction based smaller model."
# question_user: "Generate a single user_question about any topic. The question can be as simple as what is 1+1, why is the sky blue or a greeting interaction. These were just examples make the question a bit more unique."
# question_user: "Generate a single user_question about any topic. Make it relatively simple."
# question_user: "Generate a single user_question about any topic. Make it relatively simple but still the answer needs to require more than one sentance."
question_user: "Create a question that is more like an instruction for the model to start writing a story with some factual correctness in it. Basically reproducting a Novel or Wikipedia arcticle. Don't make it about hard topic tho!"

# answer_system: "Answer the user question shortly and simply. Use A1-A2 english language."
# answer_system: "Answer the user question shortly and simply."
answer_system: "Answer following the instructions."
# answer_system: "Answer the user question simply."
# answer_system: "Answer the user question."
