param_dtype: float32
compute_dtype: bfloat16

tokenizer_name: "clowman/Llama-3.2-3B-Instruct-AWQ-Int4"
# tokenizer_name: neo-english-cust
tokenizer_path: tiny_cached
tokenizer_dtype: float32 #uint16
use_custom_tokenizer: false
custom_tokenizer_path: math_tokenizer_data

# dataset_name: wikitext-2-raw-v1
# dataset_has_vendor: true
# dataset_vendor: Salesforce/wikitext
dataset_name: roneneldan/TinyStories
dataset_has_vendor: false
dataset_vendor: roneneldan
use_custom_dataset: false
dataset_path: math_dataset_arrow


model: # USE THIS IF YOU TRAIN A BIGGER MODEL ON BETTER DATA:
embedding_size: 512
context_length: 513
num_heads: 8
num_layers: 6
feed_forward_size: 2048
rope_dim: 8

num_kv_heads: 8

# training:
dropout_rate: 0.05
learning_rate: 2e-4
weight_decay: 0.05
batch_size: 8
num_epochs: 3
acc_steps: 2
ffn_activation: silu # epu

# other:
# use_remat: true
dataset_percent: 0.5
chunk_percent: 10
# put cpu if you dont have gpu, jax may do that for you
device: gpu
